/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package colorgenerator;

import java.awt.Color;
import java.awt.HeadlessException;
import java.awt.Panel;
import java.util.Random;
import javax.swing.JToggleButton;
import java.awt.datatransfer.StringSelection;
import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;

/**
 *
 * @author almarzooqih23
 */
public class ColorPallets extends javax.swing.JFrame {

    /**
     * Creates new form ColorPallets
     */
    public ColorPallets() {
        initComponents();
        colorPannel1.setBackground(Color.lightGray);
        colorPannel2.setBackground(Color.lightGray);
        colorPannel3.setBackground(Color.lightGray);
        colorPannel4.setBackground(Color.lightGray);
        copyRGBColor1.setText("");
        copyRGBColor2.setText("");
        copyRGBColor3.setText("");
        copyRGBColor4.setText("");

    }

    //This method generates a color.
    private Color makeColor() {
        Color color;
        Random random = new Random();
        //Generating a random number then multiplying it by the max value of the rgb which is 255, then rounding it and casting it into an integer.
        int red = (int) Math.round(random.nextDouble() * 255);
        int green = (int) Math.round(random.nextDouble() * 255);
        int blue = (int) Math.round(random.nextDouble() * 255);
        color = new Color(red, green, blue);
        return color;
    }

    //this method returns the rgb values.
    private String getRGBInfo(Color c) {
        return "R: " + c.getRed() + " G: " + c.getGreen() + " B: " + c.getBlue();
    }

    public ColorPallets(Panel colorPannel1, Panel colorPannel2, Panel colorPannel3, JToggleButton generateButton) throws HeadlessException {
        this.colorPannel1 = colorPannel1;
        this.colorPannel2 = colorPannel2;
        this.colorPannel3 = colorPannel3;
        this.generateButton = generateButton;
    }

    public void copyRGBValues(String s) {
        StringSelection sS = new StringSelection(s);
        Clipboard cB = Toolkit.getDefaultToolkit().getSystemClipboard();
        cB.setContents(sS, null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        colorPannel1 = new java.awt.Panel();
        label1 = new java.awt.Label();
        colorPannel2 = new java.awt.Panel();
        colorPannel3 = new java.awt.Panel();
        generateButton = new javax.swing.JToggleButton();
        colorPannel4 = new java.awt.Panel();
        copyRGBColor1 = new javax.swing.JButton();
        copyRGBColor2 = new javax.swing.JButton();
        copyRGBColor3 = new javax.swing.JButton();
        copyRGBColor4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        colorPannel1.setBackground(new java.awt.Color(255, 51, 51));

        label1.setText("label1");

        javax.swing.GroupLayout colorPannel1Layout = new javax.swing.GroupLayout(colorPannel1);
        colorPannel1.setLayout(colorPannel1Layout);
        colorPannel1Layout.setHorizontalGroup(
            colorPannel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 219, Short.MAX_VALUE)
        );
        colorPannel1Layout.setVerticalGroup(
            colorPannel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 162, Short.MAX_VALUE)
        );

        colorPannel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout colorPannel2Layout = new javax.swing.GroupLayout(colorPannel2);
        colorPannel2.setLayout(colorPannel2Layout);
        colorPannel2Layout.setHorizontalGroup(
            colorPannel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        colorPannel2Layout.setVerticalGroup(
            colorPannel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 164, Short.MAX_VALUE)
        );

        colorPannel3.setBackground(new java.awt.Color(0, 0, 255));

        javax.swing.GroupLayout colorPannel3Layout = new javax.swing.GroupLayout(colorPannel3);
        colorPannel3.setLayout(colorPannel3Layout);
        colorPannel3Layout.setHorizontalGroup(
            colorPannel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 227, Short.MAX_VALUE)
        );
        colorPannel3Layout.setVerticalGroup(
            colorPannel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 168, Short.MAX_VALUE)
        );

        generateButton.setText("Generate new colors");
        generateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateButtonActionPerformed(evt);
            }
        });

        colorPannel4.setBackground(new java.awt.Color(0, 51, 51));

        javax.swing.GroupLayout colorPannel4Layout = new javax.swing.GroupLayout(colorPannel4);
        colorPannel4.setLayout(colorPannel4Layout);
        colorPannel4Layout.setHorizontalGroup(
            colorPannel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 202, Short.MAX_VALUE)
        );
        colorPannel4Layout.setVerticalGroup(
            colorPannel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 168, Short.MAX_VALUE)
        );

        copyRGBColor1.setText("Dummy text");
        copyRGBColor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copyRGBColor1ActionPerformed(evt);
            }
        });

        copyRGBColor2.setText("Dummy text");
        copyRGBColor2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copyRGBColor2ActionPerformed(evt);
            }
        });

        copyRGBColor3.setText("Dummy text");
        copyRGBColor3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copyRGBColor3ActionPerformed(evt);
            }
        });

        copyRGBColor4.setText("Dummy text");
        copyRGBColor4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copyRGBColor4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(generateButton)
                .addGap(253, 253, 253))
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(colorPannel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(colorPannel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(copyRGBColor1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(copyRGBColor3, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(colorPannel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(colorPannel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(copyRGBColor2, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(copyRGBColor4, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(104, 104, 104))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(colorPannel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(colorPannel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(copyRGBColor1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(copyRGBColor2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(colorPannel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(colorPannel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(copyRGBColor3)
                    .addComponent(copyRGBColor4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(generateButton))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void generateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateButtonActionPerformed
        // TODO add your handling code here:
        //Generating new colors
        Color c1 = makeColor();
        Color c2 = makeColor();
        Color c3 = makeColor();
        Color c4 = makeColor();
        ///Setting the pallets to the generated colors.
        colorPannel1.setBackground(c1);
        colorPannel2.setBackground(c2);
        colorPannel3.setBackground(c3);
        colorPannel4.setBackground(c4);
        //Setting the rgb colors.
        copyRGBColor1.setText(getRGBInfo(c1));
        copyRGBColor2.setText(getRGBInfo(c2));
        copyRGBColor3.setText(getRGBInfo(c3));
        copyRGBColor4.setText(getRGBInfo(c4));

    }//GEN-LAST:event_generateButtonActionPerformed

    private void copyRGBColor3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copyRGBColor3ActionPerformed
        // TODO add your handling code here:
        copyRGBValues(copyRGBColor3.getText());
    }//GEN-LAST:event_copyRGBColor3ActionPerformed

    private void copyRGBColor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copyRGBColor2ActionPerformed
        // TODO add your handling code here:
        copyRGBValues(copyRGBColor2.getText());
    }//GEN-LAST:event_copyRGBColor2ActionPerformed

    private void copyRGBColor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copyRGBColor1ActionPerformed
        // TODO add your handling code here:
        copyRGBValues(copyRGBColor1.getText());
    }//GEN-LAST:event_copyRGBColor1ActionPerformed

    private void copyRGBColor4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copyRGBColor4ActionPerformed
        // TODO add your handling code here:
        copyRGBValues(copyRGBColor4.getText());
    }//GEN-LAST:event_copyRGBColor4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ColorPallets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ColorPallets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ColorPallets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ColorPallets.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ColorPallets().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Panel colorPannel1;
    private java.awt.Panel colorPannel2;
    private java.awt.Panel colorPannel3;
    private java.awt.Panel colorPannel4;
    private javax.swing.JButton copyRGBColor1;
    private javax.swing.JButton copyRGBColor2;
    private javax.swing.JButton copyRGBColor3;
    private javax.swing.JButton copyRGBColor4;
    private javax.swing.JToggleButton generateButton;
    private java.awt.Label label1;
    // End of variables declaration//GEN-END:variables
}
